spring.application.name=Main

spring.datasource.url = jdbc:mysql://localhost:3306/ananda
spring.datasource.username = root
spring.datasource.password = admin@123

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
